/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Users/thedelanocompany/opt/anaconda3/bin/python: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/thedelanocompany/Documents/GitHub/SocioSync Contact Manager/SOCIOSYNC/manage.py': [Errno 1] Operation not permitted
